function add_myfnc_path(fnc_pdir)

path(path,fullfile(fnc_pdir,'other'))
path(path,fullfile(fnc_pdir,'ez'))
path(path,fullfile(fnc_pdir,'filtering'))
path(path,fullfile(fnc_pdir,'mpo'))
path(path,fullfile(fnc_pdir,'unit_trans'))
path(path,fullfile(fnc_pdir,'wave_manipulator'))
path(path,fullfile(fnc_pdir,'processing'))
path(path,fullfile(fnc_pdir,'fft_assistant'))
path(path,fullfile(fnc_pdir,'evp_manipulator'))
path(path,fullfile(fnc_pdir,'gmug'))
path(path,fullfile(fnc_pdir,'iss_wave_manipulator'))
path(path,fullfile(fnc_pdir,'jdi_manipulator'))
path(path,fullfile(fnc_pdir,'trans_coordinates'))
path(path,fullfile(fnc_pdir,'repeater_analysis'))
path(path,fullfile(fnc_pdir,'color_map_manipulator'))
path(path,fullfile(fnc_pdir,'figure_formating'))
path(path,fullfile(fnc_pdir,'win_path_control'))
path(path,fullfile(fnc_pdir,'3D_geometry'))
path(path,fullfile(fnc_pdir,'strain_analysis'))
path(path,fullfile(fnc_pdir,'ez_PXI_analysis'))
path(path,fullfile(fnc_pdir,'hypo_manipulator'))


